[package]
name = "bloqr-validator-core-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "CLI tool for AdGuard filter validation"

[[bin]]
name = "rules-validate"
path = "src/main.rs"

[dependencies]
rules_validator = { path = "../rules-validator-core", package = "bloqr-validator-core" }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
