using System.Globalization;
using System.Text;

namespace Bloqr.Dashboard.Core.Configuration;

/// <summary>
/// Emits the Dashboard's configuration as a heavily-commented <c>.jsonc</c> document, per the
/// epic's explicit requirement that the Dashboard's own config format be JSONC specifically so
/// it can carry comments. The document is always regenerated in full from the in-memory model on
/// save: the Dashboard owns and fully controls this file's shape, so — unlike e.g. a
/// hand-authored <c>deno.json</c> — there is no third-party-authored content whose comments must
/// be preserved across a round trip.
/// </summary>
public static class JsoncWriter
{
    /// <summary>
    /// Renders a <see cref="DashboardConfiguration"/> as a heavily-commented JSONC document.
    /// </summary>
    /// <param name="configuration">The configuration to render.</param>
    /// <returns>The JSONC document text.</returns>
    public static string Write(DashboardConfiguration configuration)
    {
        ArgumentNullException.ThrowIfNull(configuration);

        var sb = new StringBuilder();

        sb.AppendLine("// Bloqr Dashboard configuration file.");
        sb.AppendLine("// This file is JSONC (JSON with Comments) and is regenerated by the Dashboard on every save.");
        sb.AppendLine("// Schema: https://github.com/BloqrAI/bloqr-core/schemas/dashboard-config.schema.json");
        sb.AppendLine("{");

        AppendLine(sb, 1, "// Dashboard config schema version, for migration/compatibility checks.");
        AppendLine(sb, 1, $"\"version\": {JsonString(configuration.Version)},");
        sb.AppendLine();

        AppendLine(sb, 1, "// Global default settings, used when no profile is active or as fallback");
        AppendLine(sb, 1, "// values for a profile that doesn't override them.");
        AppendLine(sb, 1, "\"settings\": {");
        AppendSettingsBody(sb, 2, configuration.Settings);
        AppendLine(sb, 1, "},");
        sb.AppendLine();

        AppendLine(sb, 1, "// Named profiles: collections of settings overrides plus references to one");
        AppendLine(sb, 1, "// or more compiler-config files. Keyed by profile name.");
        if (configuration.Profiles.Count == 0)
        {
            AppendLine(sb, 1, "\"profiles\": {}");
        }
        else
        {
            AppendLine(sb, 1, "\"profiles\": {");
            AppendProfiles(sb, 2, configuration.Profiles);
            AppendLine(sb, 1, "}");
        }

        sb.Append('}');
        sb.AppendLine();
        return sb.ToString();
    }

    private static void AppendSettingsBody(StringBuilder sb, int level, DashboardSettings settings)
    {
        AppendLine(sb, level, "// Console UI color theme: \"default\", \"dark\", \"light\", or \"high-contrast\".");
        AppendLine(sb, level, $"\"theme\": {JsonString(DashboardThemeJsonConverter.ToSchemaValue(settings.Theme))},");
        Blank(sb);

        AppendLine(sb, level, "// Default log verbosity: \"trace\", \"debug\", \"info\", \"warn\", \"error\", or \"silent\".");
        AppendLine(sb, level, "// Defaults to \"error\": the Dashboard should stay quiet unless something is wrong.");
        AppendLine(sb, level, $"\"logLevel\": {JsonString(DashboardLogLevelJsonConverter.ToSchemaValue(settings.LogLevel))},");
        Blank(sb);

        AppendLine(sb, level, "// Default directory compiled output is copied to when --copy-to-rules is used.");
        AppendLine(sb, level, $"\"defaultRulesDirectory\": {JsonString(settings.DefaultRulesDirectory)},");
        Blank(sb);

        AppendLine(sb, level, "// Backup/restore settings for this Dashboard config and any compiler configs it references.");
        AppendLine(sb, level, "\"backup\": {");
        AppendBackupBody(sb, level + 1, settings.Backup);
        AppendLine(sb, level, "},");
        Blank(sb);

        AppendLine(sb, level, "// Name of the currently active profile (must match a key in \"profiles\"), or null if none active.");
        AppendLine(sb, level, $"\"activeProfile\": {JsonString(settings.ActiveProfile)}");
    }

    private static void AppendBackupBody(StringBuilder sb, int level, BackupSettings backup)
    {
        AppendLine(sb, level, $"\"enabled\": {JsonBool(backup.Enabled)},");
        AppendLine(sb, level, $"\"maxBackups\": {JsonNumber(backup.MaxBackups)},");
        AppendLine(sb, level, $"\"backupDirectory\": {JsonString(backup.BackupDirectory)}");
    }

    private static void AppendProfiles(StringBuilder sb, int level, IReadOnlyDictionary<string, DashboardProfile> profiles)
    {
        var entries = profiles.ToList();
        for (var i = 0; i < entries.Count; i++)
        {
            var (name, profile) = entries[i];
            var isLast = i == entries.Count - 1;

            AppendLine(sb, level, $"{JsonString(name)}: {{");
            AppendProfileBody(sb, level + 1, profile);
            AppendLine(sb, level, isLast ? "}" : "},");
        }
    }

    private static void AppendProfileBody(StringBuilder sb, int level, DashboardProfile profile)
    {
        if (!string.IsNullOrWhiteSpace(profile.Description))
        {
            AppendLine(sb, level, $"\"description\": {JsonString(profile.Description)},");
        }

        if (profile.SettingsOverrides is { } overrides)
        {
            AppendLine(sb, level, "\"settingsOverrides\": {");
            AppendSettingsOverridesBody(sb, level + 1, overrides);
            AppendLine(sb, level, "},");
        }

        AppendLine(sb, level, "// Paths to one or more compiler-config files that make up this profile.");
        AppendLine(sb, level, $"\"compilerConfigs\": [{string.Join(", ", profile.CompilerConfigs.Select(JsonString))}]");
    }

    private static void AppendSettingsOverridesBody(StringBuilder sb, int level, DashboardSettingsOverrides overrides)
    {
        var lines = new List<string>();

        if (overrides.Theme is { } theme)
        {
            lines.Add($"\"theme\": {JsonString(DashboardThemeJsonConverter.ToSchemaValue(theme))}");
        }

        if (overrides.LogLevel is { } logLevel)
        {
            lines.Add($"\"logLevel\": {JsonString(DashboardLogLevelJsonConverter.ToSchemaValue(logLevel))}");
        }

        if (overrides.DefaultRulesDirectory is { } directory)
        {
            lines.Add($"\"defaultRulesDirectory\": {JsonString(directory)}");
        }

        if (overrides.Backup is { } backup)
        {
            lines.Add(
                $"\"backup\": {{ \"enabled\": {JsonBool(backup.Enabled)}, " +
                $"\"maxBackups\": {JsonNumber(backup.MaxBackups)}, " +
                $"\"backupDirectory\": {JsonString(backup.BackupDirectory)} }}");
        }

        for (var i = 0; i < lines.Count; i++)
        {
            AppendLine(sb, level, i == lines.Count - 1 ? lines[i] : lines[i] + ",");
        }
    }

    private static void AppendLine(StringBuilder sb, int level, string text)
    {
        sb.Append(' ', level * 2);
        sb.AppendLine(text);
    }

    private static void Blank(StringBuilder sb) => sb.AppendLine();

    private static string JsonString(string? value) =>
        value is null ? "null" : JsonSerializer.Serialize(value);

    private static string JsonBool(bool value) => value ? "true" : "false";

    private static string JsonNumber(int value) => value.ToString(CultureInfo.InvariantCulture);
}
