//! C-compatible FFI surface for `bloqr-validator-core`.
//!
//! Exposes [`Validator`] over an opaque-handle + JSON-string boundary, so
//! callers (.NET P/Invoke, or any other FFI consumer) only need to marshal
//! a pointer and a handful of null-terminated strings — no field-by-field
//! struct layout to keep in sync across the ABI.
//!
//! ## Conventions
//!
//! - Every function that can fail returns an [`FfiStatus`] code.
//! - Complex return data (validation results) is written through an
//!   `out_result_json: *mut *mut c_char` out-parameter as a JSON string.
//!   The caller owns that string and **must** free it with
//!   [`rules_validator_free_string`].
//! - `rules_validator_new` takes an optional JSON-encoded [`ValidationConfig`]
//!   (pass `NULL` for defaults) and returns an opaque handle, or `NULL` on
//!   failure. The handle must be freed with [`rules_validator_free`].
//! - No function panics across the FFI boundary — `catch_unwind` guards
//!   every entry point, converting a Rust panic into [`FfiStatus::Panic`].
//!
//! See `src/rules-validator/README.md` for a full P/Invoke usage example
//! and `rules_validator.h` (generated by `cbindgen`) for the C header.

use std::ffi::{c_char, CStr, CString};
use std::panic::{catch_unwind, AssertUnwindSafe};
use std::ptr;

use crate::config::ValidationConfig;
use crate::validator::Validator;

/// Status codes returned by every fallible FFI function.
#[repr(i32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FfiStatus {
    /// Call succeeded; any out-parameters are populated.
    Success = 0,
    /// A required pointer argument was null.
    NullPointer = -1,
    /// A `*const c_char` argument was not valid UTF-8.
    InvalidUtf8 = -2,
    /// A JSON argument (e.g. the config passed to `rules_validator_new`)
    /// failed to parse.
    InvalidJson = -3,
    /// The validation operation itself failed; the out-parameter JSON
    /// (when present) contains the error message.
    ValidationFailed = -4,
    /// A Rust panic was caught at the FFI boundary.
    Panic = -5,
}

/// Creates a new validator from an optional JSON-encoded [`ValidationConfig`].
///
/// Pass `NULL` for `config_json` to use [`ValidationConfig::default`].
///
/// Returns an opaque handle to be passed to the other `rules_validator_*`
/// functions, or `NULL` if `config_json` was provided but failed to parse.
/// The returned handle must be released with [`rules_validator_free`].
///
/// # Safety
///
/// `config_json`, if non-null, must point to a valid null-terminated UTF-8
/// C string.
#[no_mangle]
pub unsafe extern "C" fn rules_validator_new(config_json: *const c_char) -> *mut Validator {
    let result = catch_unwind(AssertUnwindSafe(|| {
        let config = if config_json.is_null() {
            ValidationConfig::default()
        } else {
            let Ok(s) = CStr::from_ptr(config_json).to_str() else {
                return None;
            };
            let Ok(config) = serde_json::from_str::<ValidationConfig>(s) else {
                return None;
            };
            config
        };

        Some(Box::into_raw(Box::new(Validator::new(config))))
    }));

    match result {
        Ok(Some(ptr)) => ptr,
        Ok(None) | Err(_) => ptr::null_mut(),
    }
}

/// Releases a validator handle created by [`rules_validator_new`].
///
/// # Safety
///
/// `validator` must be a pointer previously returned by
/// [`rules_validator_new`] and not already freed. Passing `NULL` is a no-op.
#[no_mangle]
pub unsafe extern "C" fn rules_validator_free(validator: *mut Validator) {
    if !validator.is_null() {
        drop(Box::from_raw(validator));
    }
}

/// Validates a local file (syntax + at-rest hash verification).
///
/// On success or a validation failure, `*out_result_json` is set to an
/// owned, null-terminated JSON string describing the result (or the error)
/// which the caller must free with [`rules_validator_free_string`].
///
/// # Safety
///
/// `validator` must be a live handle from [`rules_validator_new`]. `path`
/// must point to a valid null-terminated UTF-8 C string. `out_result_json`
/// must point to valid, writable memory for a `*mut c_char`.
#[no_mangle]
pub unsafe extern "C" fn rules_validator_validate_local_file(
    validator: *mut Validator,
    path: *const c_char,
    out_result_json: *mut *mut c_char,
) -> FfiStatus {
    if validator.is_null() || path.is_null() || out_result_json.is_null() {
        return FfiStatus::NullPointer;
    }

    let Ok(path_str) = CStr::from_ptr(path).to_str() else {
        return FfiStatus::InvalidUtf8;
    };

    let result = catch_unwind(AssertUnwindSafe(|| {
        let validator = &mut *validator;
        validator.validate_local_file(path_str)
    }));

    match result {
        Ok(Ok(validation_result)) => {
            write_json_out(out_result_json, &validation_result);
            FfiStatus::Success
        }
        Ok(Err(err)) => {
            write_json_out(out_result_json, &FfiError::from(&err));
            FfiStatus::ValidationFailed
        }
        Err(_) => FfiStatus::Panic,
    }
}

/// Validates a remote URL (security checks, HTTPS enforcement, optional
/// in-flight hash verification).
///
/// `expected_hash` may be `NULL` to skip in-flight hash verification.
///
/// On success or a validation failure, `*out_result_json` is set to an
/// owned, null-terminated JSON string describing the result (or the error)
/// which the caller must free with [`rules_validator_free_string`].
///
/// # Safety
///
/// `validator` must be a live handle from [`rules_validator_new`]. `url`
/// must point to a valid null-terminated UTF-8 C string; `expected_hash`
/// must be either `NULL` or a valid null-terminated UTF-8 C string.
/// `out_result_json` must point to valid, writable memory for a
/// `*mut c_char`.
#[no_mangle]
pub unsafe extern "C" fn rules_validator_validate_remote_url(
    validator: *const Validator,
    url: *const c_char,
    expected_hash: *const c_char,
    out_result_json: *mut *mut c_char,
) -> FfiStatus {
    if validator.is_null() || url.is_null() || out_result_json.is_null() {
        return FfiStatus::NullPointer;
    }

    let Ok(url_str) = CStr::from_ptr(url).to_str() else {
        return FfiStatus::InvalidUtf8;
    };

    let expected_hash_str = if expected_hash.is_null() {
        None
    } else {
        match CStr::from_ptr(expected_hash).to_str() {
            Ok(s) => Some(s),
            Err(_) => return FfiStatus::InvalidUtf8,
        }
    };

    let result = catch_unwind(AssertUnwindSafe(|| {
        let validator = &*validator;
        validator.validate_remote_url(url_str, expected_hash_str)
    }));

    match result {
        Ok(Ok(validation_result)) => {
            write_json_out(out_result_json, &validation_result);
            FfiStatus::Success
        }
        Ok(Err(err)) => {
            write_json_out(out_result_json, &FfiError::from(&err));
            FfiStatus::ValidationFailed
        }
        Err(_) => FfiStatus::Panic,
    }
}

/// Returns the library version as an owned, null-terminated C string.
///
/// The caller must free the returned string with
/// [`rules_validator_free_string`].
#[no_mangle]
pub extern "C" fn rules_validator_version() -> *mut c_char {
    // CARGO_PKG_VERSION is a valid UTF-8 compile-time constant; unwrap is safe.
    CString::new(crate::VERSION).unwrap().into_raw()
}

/// Frees a string previously returned by any `rules_validator_*` function
/// (via an `out_result_json` parameter, or [`rules_validator_version`]).
///
/// # Safety
///
/// `s` must be a pointer previously returned by one of this module's
/// functions and not already freed. Passing `NULL` is a no-op.
#[no_mangle]
pub unsafe extern "C" fn rules_validator_free_string(s: *mut c_char) {
    if !s.is_null() {
        drop(CString::from_raw(s));
    }
}

/// JSON-serializable error envelope for the FFI boundary.
#[derive(serde::Serialize)]
struct FfiError {
    error: String,
}

impl From<&crate::error::ValidationError> for FfiError {
    fn from(err: &crate::error::ValidationError) -> Self {
        Self {
            error: err.to_string(),
        }
    }
}

/// Serializes `value` to JSON and writes it into `out` as an owned C string.
/// On serialization failure (should not happen for our result types),
/// writes a minimal fallback JSON error string instead of leaving `out`
/// uninitialized.
fn write_json_out<T: serde::Serialize>(out: *mut *mut c_char, value: &T) {
    let json = serde_json::to_string(value)
        .unwrap_or_else(|e| format!("{{\"error\":\"failed to serialize result: {e}\"}}"));
    // CString::new fails only on interior NUL bytes, which valid JSON text
    // never contains.
    let c_string = CString::new(json)
        .unwrap_or_else(|_| CString::new("{\"error\":\"result contained a NUL byte\"}").unwrap());
    unsafe {
        *out = c_string.into_raw();
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use tempfile::NamedTempFile;

    fn cstr(s: &str) -> CString {
        CString::new(s).unwrap()
    }

    #[test]
    fn test_new_with_null_config_uses_defaults() {
        unsafe {
            let handle = rules_validator_new(ptr::null());
            assert!(!handle.is_null());
            rules_validator_free(handle);
        }
    }

    #[test]
    fn test_new_with_valid_json_config() {
        let config = ValidationConfig::default();
        let json = serde_json::to_string(&config).unwrap();
        let c_json = cstr(&json);

        unsafe {
            let handle = rules_validator_new(c_json.as_ptr());
            assert!(!handle.is_null());
            rules_validator_free(handle);
        }
    }

    #[test]
    fn test_new_with_invalid_json_returns_null() {
        let c_json = cstr("not valid json");

        unsafe {
            let handle = rules_validator_new(c_json.as_ptr());
            assert!(handle.is_null());
        }
    }

    #[test]
    fn test_free_null_handle_is_noop() {
        unsafe {
            rules_validator_free(ptr::null_mut());
        }
    }

    #[test]
    fn test_validate_local_file_round_trip() {
        use tempfile::TempDir;

        let dir = TempDir::new().unwrap();
        let hash_db_path = dir.path().join(".hashes.json");

        let mut config = ValidationConfig::default();
        config.hash_verification.hash_database_path = hash_db_path.display().to_string();
        let config_json = cstr(&serde_json::to_string(&config).unwrap());

        let mut file = NamedTempFile::new().unwrap();
        writeln!(file, "||example.com^").unwrap();
        writeln!(file, "@@||allowed.com").unwrap();
        file.flush().unwrap();

        let path_c = cstr(file.path().to_str().unwrap());

        unsafe {
            let handle = rules_validator_new(config_json.as_ptr());
            assert!(!handle.is_null());

            let mut out_json: *mut c_char = ptr::null_mut();
            let status =
                rules_validator_validate_local_file(handle, path_c.as_ptr(), &mut out_json);

            assert_eq!(status, FfiStatus::Success);
            assert!(!out_json.is_null());

            let json_str = CStr::from_ptr(out_json).to_str().unwrap();
            assert!(json_str.contains("\"is_valid\":true"));
            assert!(json_str.contains("\"valid_rules\""));

            rules_validator_free_string(out_json);
            rules_validator_free(handle);
        }
    }

    #[test]
    fn test_validate_local_file_null_pointer_args() {
        unsafe {
            let handle = rules_validator_new(ptr::null());
            let mut out_json: *mut c_char = ptr::null_mut();

            // Null path
            let status = rules_validator_validate_local_file(handle, ptr::null(), &mut out_json);
            assert_eq!(status, FfiStatus::NullPointer);

            // Null validator
            let path_c = cstr("/nonexistent");
            let status = rules_validator_validate_local_file(
                ptr::null_mut(),
                path_c.as_ptr(),
                &mut out_json,
            );
            assert_eq!(status, FfiStatus::NullPointer);

            rules_validator_free(handle);
        }
    }

    #[test]
    fn test_validate_remote_url_http_rejected() {
        let url_c = cstr("http://insecure.example.com/list.txt");

        unsafe {
            let handle = rules_validator_new(ptr::null());
            let mut out_json: *mut c_char = ptr::null_mut();

            let status = rules_validator_validate_remote_url(
                handle,
                url_c.as_ptr(),
                ptr::null(),
                &mut out_json,
            );

            // URL validation returning is_valid: false is still a
            // successful *call* (Rust-side Ok(UrlValidationResult)).
            assert_eq!(status, FfiStatus::Success);
            assert!(!out_json.is_null());

            let json_str = CStr::from_ptr(out_json).to_str().unwrap();
            assert!(json_str.contains("\"is_valid\":false"));

            rules_validator_free_string(out_json);
            rules_validator_free(handle);
        }
    }

    #[test]
    fn test_version_returns_nonempty_string() {
        unsafe {
            let v = rules_validator_version();
            assert!(!v.is_null());
            let s = CStr::from_ptr(v).to_str().unwrap();
            assert!(!s.is_empty());
            rules_validator_free_string(v);
        }
    }

    #[test]
    fn test_free_string_null_is_noop() {
        unsafe {
            rules_validator_free_string(ptr::null_mut());
        }
    }
}
