/**
 * Output format converters for filter lists.
 * Converts adblock-style rules to various output formats.
 */

import { OutputFormat } from '../config/defaults.ts';
import { RuleUtils } from '../utils/RuleUtils.ts';
import { PACKAGE_INFO } from '../version.ts';

/**
 * Options for output formatting
 */
export interface FormatterOptions {
  /** Include header comments */
  includeHeader?: boolean;
  /** Filter list name for headers */
  listName?: string;
  /** IP address to use for hosts format (default: 0.0.0.0) */
  hostsIp?: string;
  /** Include localhost entries in hosts format */
  includeLocalhost?: boolean;
}

/**
 * Result of formatting operation
 */
export interface FormatterResult {
  /** Formatted content as string */
  content: string;
  /** Number of rules included */
  ruleCount: number;
  /** Number of rules skipped (not convertible) */
  skippedCount: number;
  /** Output format used */
  format: OutputFormat;
}

/**
 * Base class for output formatters.
 * Extend this class to create custom output formatters.
 */
export abstract class BaseFormatter {
  /** Formatter options */
  protected readonly options: FormatterOptions;

  /**
   * Creates a new formatter
   * @param options - Formatter options
   */
  constructor(options?: FormatterOptions) {
    this.options = {
      includeHeader: true,
      listName: 'Filter List',
      hostsIp: '0.0.0.0',
      includeLocalhost: false,
      ...options,
    };
  }

  /**
   * Formats rules to the target format
   */
  abstract format(rules: string[]): FormatterResult;

  /**
   * Extracts hostname from an adblock rule
   */
  protected extractHostname(rule: string): string | null {
    // Skip comments and empty lines
    if (!rule || rule.startsWith('!') || rule.startsWith('#')) {
      return null;
    }

    // Skip exception rules
    if (rule.startsWith('@@')) {
      return null;
    }

    // Try to parse as adblock rule
    try {
      const parsed = RuleUtils.loadAdblockRuleProperties(rule);
      if (parsed.hostname && !parsed.whitelist) {
        return parsed.hostname;
      }
    } catch {
      // Not a valid adblock rule
    }

    // Check if it's a plain domain
    if (RuleUtils.isJustDomain(rule)) {
      return rule;
    }

    // Try to extract from simple patterns
    const match = rule.match(/^\|\|([a-z0-9.-]+)\^?$/i);
    if (match) {
      return match[1];
    }

    return null;
  }

  /**
   * Generates a header comment
   */
  protected generateHeader(commentPrefix: string): string[] {
    const lines = [
      `${commentPrefix} ${this.options.listName}`,
      `${commentPrefix} Generated by ${PACKAGE_INFO.name} v${PACKAGE_INFO.version}`,
      `${commentPrefix} Last updated: ${new Date().toISOString()}`,
      '',
    ];
    return lines;
  }
}

/**
 * Template-method base class for formats that render one line per unique
 * blocked hostname (hosts, dnsmasq, Pi-hole, Unbound, DoH, …).
 *
 * The `format()` algorithm — header, preamble, hostname extraction,
 * deduplication, and skipped-rule counting — lives here once. Subclasses only
 * declare *what a hostname line looks like*:
 *
 * ```ts
 * class RpzFormatter extends HostnameListFormatter {
 *     protected readonly outputFormat = 'rpz';
 *     protected formatHostnameLine(hostname: string): string {
 *         return `${hostname} CNAME .`;
 *     }
 * }
 * ```
 *
 * Override {@link preambleLines} for fixed lines between the header and the
 * hostname list (e.g. Unbound's `server:`), and {@link shouldIncludeHeader}
 * to opt out of the generated header entirely.
 */
export abstract class HostnameListFormatter extends BaseFormatter {
  /** Output format identifier reported in the {@link FormatterResult} */
  protected abstract readonly outputFormat: OutputFormat | string;

  /** Comment prefix used for the generated header */
  protected readonly commentPrefix: string = '#';

  /**
   * Renders a single unique hostname as one output line.
   */
  protected abstract formatHostnameLine(hostname: string): string;

  /**
   * Fixed lines emitted after the header and before the hostname list.
   * Defaults to none.
   */
  protected preambleLines(): string[] {
    return [];
  }

  /**
   * Whether the generated header is emitted when `options.includeHeader`
   * is set. Formats without comment support override this to return false.
   */
  protected shouldIncludeHeader(): boolean {
    return this.options.includeHeader === true;
  }

  /**
   * Formats rules by extracting and deduplicating hostnames, delegating
   * per-line rendering to the subclass.
   * @param rules - Array of rules to format
   * @returns Formatter result
   */
  format(rules: string[]): FormatterResult {
    const lines: string[] = [];
    let ruleCount = 0;
    let skippedCount = 0;

    if (this.shouldIncludeHeader()) {
      lines.push(...this.generateHeader(this.commentPrefix));
    }

    lines.push(...this.preambleLines());

    const seenHostnames = new Set<string>();

    for (const rule of rules) {
      const hostname = this.extractHostname(rule);
      if (hostname && !seenHostnames.has(hostname)) {
        seenHostnames.add(hostname);
        lines.push(this.formatHostnameLine(hostname));
        ruleCount++;
      } else if (hostname === null && rule && !rule.startsWith('!')) {
        skippedCount++;
      }
    }

    return {
      content: lines.join('\n'),
      ruleCount,
      skippedCount,
      format: this.outputFormat as OutputFormat,
    };
  }
}

/**
 * Formats rules to /etc/hosts format
 */
export class HostsFormatter extends HostnameListFormatter {
  /** Always `OutputFormat.Hosts`. */
  protected override readonly outputFormat: OutputFormat = OutputFormat.Hosts;

  /** Prepends `localhost` entries when `options.includeLocalhost` is set. */
  protected override preambleLines(): string[] {
    // Add localhost entries if requested
    if (this.options.includeLocalhost) {
      return ['127.0.0.1 localhost', '::1 localhost', ''];
    }
    return [];
  }

  /**
   * Formats a hostname as an `/etc/hosts` line.
   * @param hostname The hostname to format.
   * @returns `"<hostsIp> <hostname>"`, using `options.hostsIp` (default `0.0.0.0`).
   */
  protected override formatHostnameLine(hostname: string): string {
    return `${this.options.hostsIp} ${hostname}`;
  }
}

/**
 * Formats rules to dnsmasq format
 */
export class DnsmasqFormatter extends HostnameListFormatter {
  /** Always `OutputFormat.Dnsmasq`. */
  protected override readonly outputFormat: OutputFormat = OutputFormat.Dnsmasq;

  /**
   * Formats a hostname as a dnsmasq `address=` directive.
   * @param hostname The hostname to format.
   * @returns `"address=/<hostname>/"`.
   */
  protected override formatHostnameLine(hostname: string): string {
    return `address=/${hostname}/`;
  }
}

/**
 * Formats rules to Pi-hole format (domain list)
 */
export class PiHoleFormatter extends HostnameListFormatter {
  /** Always `OutputFormat.PiHole`. */
  protected override readonly outputFormat: OutputFormat = OutputFormat.PiHole;

  /**
   * Formats a hostname as a bare domain-list line.
   * @param hostname The hostname to format.
   * @returns `hostname`, unchanged.
   */
  protected override formatHostnameLine(hostname: string): string {
    return hostname;
  }
}

/**
 * Formats rules to Unbound DNS resolver format
 */
export class UnboundFormatter extends HostnameListFormatter {
  /** Always `OutputFormat.Unbound`. */
  protected override readonly outputFormat: OutputFormat = OutputFormat.Unbound;

  /** Emits the `server:` block header Unbound requires before `local-zone` directives. */
  protected override preambleLines(): string[] {
    return ['server:'];
  }

  /**
   * Formats a hostname as an Unbound `local-zone` directive.
   * @param hostname The hostname to format.
   * @returns `'    local-zone: "<hostname>" always_nxdomain'`.
   */
  protected override formatHostnameLine(hostname: string): string {
    return `    local-zone: "${hostname}" always_nxdomain`;
  }
}

/**
 * Formats rules to JSON format
 */
export class JsonFormatter extends BaseFormatter {
  /**
   * Formats rules to JSON format
   * @param rules - Array of rules to format
   * @returns Formatted result
   */
  format(rules: string[]): FormatterResult {
    const hostnames: string[] = [];
    const allRules: string[] = [];
    let skippedCount = 0;

    const seenHostnames = new Set<string>();

    for (const rule of rules) {
      if (!rule || rule.startsWith('!')) {
        continue;
      }

      allRules.push(rule);

      const hostname = this.extractHostname(rule);
      if (hostname && !seenHostnames.has(hostname)) {
        seenHostnames.add(hostname);
        hostnames.push(hostname);
      } else if (hostname === null) {
        skippedCount++;
      }
    }

    const output = {
      name: this.options.listName,
      generated: new Date().toISOString(),
      generator: `${PACKAGE_INFO.name} v${PACKAGE_INFO.version}`,
      stats: {
        totalRules: allRules.length,
        uniqueHostnames: hostnames.length,
        skippedRules: skippedCount,
      },
      hostnames,
      rules: allRules,
    };

    return {
      content: JSON.stringify(output, null, 2),
      ruleCount: hostnames.length,
      skippedCount,
      format: OutputFormat.JSON,
    };
  }
}

/**
 * Formats rules to DNS-over-HTTPS blocklist format
 */
export class DoHFormatter extends HostnameListFormatter {
  /** Always `OutputFormat.DoH`. */
  protected override readonly outputFormat: OutputFormat = OutputFormat.DoH;

  /** Always `false` — DoH blocklists are plain domain lists with no comment header. */
  protected override shouldIncludeHeader(): boolean {
    // DoH blocklists are plain domain lists with no comment lines
    return false;
  }

  /**
   * Formats a hostname as a bare domain-list line.
   * @param hostname The hostname to format.
   * @returns `hostname`, unchanged.
   */
  protected override formatHostnameLine(hostname: string): string {
    return hostname;
  }
}

/**
 * Adblock format passthrough (no conversion)
 */
export class AdblockFormatter extends BaseFormatter {
  /**
   * Formats rules in adblock format (passthrough)
   * @param rules - Array of rules to format
   * @returns Formatted result
   */
  format(rules: string[]): FormatterResult {
    return {
      content: rules.join('\n'),
      ruleCount: rules.filter((r) => r && !r.startsWith('!')).length,
      skippedCount: 0,
      format: OutputFormat.Adblock,
    };
  }
}

/**
 * Constructor type for formatters
 */
export type FormatterConstructor = new (options?: FormatterOptions) => BaseFormatter;

/**
 * Extensible formatter factory with registration pattern.
 * Allows registering custom formatters for new output formats.
 */
export class FormatterFactory {
  private static readonly formatters = new Map<OutputFormat | string, FormatterConstructor>();
  private static readonly defaultFormat: OutputFormat = OutputFormat.Adblock;

  /**
   * Register a formatter for a given output format.
   * Can override built-in formatters or add new ones.
   * @param format - Output format identifier
   * @param formatterClass - Formatter constructor
   */
  static register(format: OutputFormat | string, formatterClass: FormatterConstructor): void {
    FormatterFactory.formatters.set(format, formatterClass);
  }

  /**
   * Unregister a formatter
   * @param format - Output format to unregister
   * @returns true if the format was registered and removed
   */
  static unregister(format: OutputFormat | string): boolean {
    return FormatterFactory.formatters.delete(format);
  }

  /**
   * Check if a format is registered
   * @param format - Output format to check
   */
  static has(format: OutputFormat | string): boolean {
    return FormatterFactory.formatters.has(format);
  }

  /**
   * Get all registered format names
   */
  static getRegisteredFormats(): (OutputFormat | string)[] {
    return Array.from(FormatterFactory.formatters.keys());
  }

  /**
   * Create a formatter instance for the given format
   * @param format - Output format
   * @param options - Formatter options
   * @returns Formatter instance
   * @throws Error if format is not registered
   */
  static create(format: OutputFormat | string, options?: FormatterOptions): BaseFormatter {
    const FormatterClass = FormatterFactory.formatters.get(format);

    if (!FormatterClass) {
      // Fall back to default formatter if unknown format
      const DefaultClass = FormatterFactory.formatters.get(FormatterFactory.defaultFormat);
      if (DefaultClass) {
        return new DefaultClass(options);
      }
      throw new Error(`Unknown format: ${format} and no default formatter registered`);
    }

    return new FormatterClass(options);
  }

  /**
   * Initialize factory with built-in formatters.
   * Called automatically on module load.
   */
  static initialize(): void {
    FormatterFactory.register(OutputFormat.Hosts, HostsFormatter);
    FormatterFactory.register(OutputFormat.Dnsmasq, DnsmasqFormatter);
    FormatterFactory.register(OutputFormat.PiHole, PiHoleFormatter);
    FormatterFactory.register(OutputFormat.Unbound, UnboundFormatter);
    FormatterFactory.register(OutputFormat.JSON, JsonFormatter);
    FormatterFactory.register(OutputFormat.DoH, DoHFormatter);
    FormatterFactory.register(OutputFormat.Adblock, AdblockFormatter);
  }
}

// Initialize built-in formatters on module load
FormatterFactory.initialize();

/**
 * Factory function to create formatters (backward compatible wrapper)
 * @deprecated Use FormatterFactory.create() instead
 */
export function createFormatter(format: OutputFormat, options?: FormatterOptions): BaseFormatter {
  return FormatterFactory.create(format, options);
}

/**
 * Formats rules to the specified output format
 */
export function formatOutput(
  rules: string[],
  format: OutputFormat | string,
  options?: FormatterOptions,
): FormatterResult {
  const formatter = FormatterFactory.create(format, options);
  return formatter.format(rules);
}
