/*
 * bloqr_validator.h — C header for bloqr-validator-core's FFI surface.
 *
 * Generated by cbindgen from src/ffi.rs. Do not edit by hand — regenerate
 * with (run from src/validation/core/):
 *
 *   cargo install cbindgen
 *   cbindgen --config cbindgen.toml --crate bloqr-validator-core \
 *     --output bloqr_validator.h
 *
 * See src/ffi.rs's module doc for usage conventions (opaque handle,
 * caller-owns-and-frees-strings, JSON-encoded results/errors).
 */


#ifndef BLOQR_VALIDATOR_H
#define BLOQR_VALIDATOR_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Status codes returned by every fallible FFI function.
 */
enum FfiStatus
#if __STDC_VERSION__ >= 202311L
  : int32_t
#endif // __STDC_VERSION__ >= 202311L
 {
    /**
     * Call succeeded; any out-parameters are populated.
     */
    Success = 0,
    /**
     * A required pointer argument was null.
     */
    NullPointer = -1,
    /**
     * A `*const c_char` argument was not valid UTF-8.
     */
    InvalidUtf8 = -2,
    /**
     * A JSON argument (e.g. the config passed to `bloqr_validator_new`)
     * failed to parse.
     */
    InvalidJson = -3,
    /**
     * The validation operation itself failed; the out-parameter JSON
     * (when present) contains the error message.
     */
    ValidationFailed = -4,
    /**
     * A Rust panic was caught at the FFI boundary.
     */
    Panic = -5,
};
#if __STDC_VERSION__ >= 202311L
typedef enum FfiStatus FfiStatus;
#else
typedef int32_t FfiStatus;
#endif // __STDC_VERSION__ >= 202311L

/**
 * Main validator for filter lists.
 */
typedef struct Validator Validator;

/**
 * Creates a new validator from an optional JSON-encoded [`ValidationConfig`].
 *
 * Pass `NULL` for `config_json` to use [`ValidationConfig::default`].
 *
 * Returns an opaque handle to be passed to the other `bloqr_validator_*`
 * functions, or `NULL` if `config_json` was provided but failed to parse.
 * The returned handle must be released with [`bloqr_validator_free`].
 *
 * # Safety
 *
 * `config_json`, if non-null, must point to a valid null-terminated UTF-8
 * C string.
 */
 struct Validator *bloqr_validator_new(const char *config_json);

/**
 * Releases a validator handle created by [`bloqr_validator_new`].
 *
 * # Safety
 *
 * `validator` must be a pointer previously returned by
 * [`bloqr_validator_new`] and not already freed. Passing `NULL` is a no-op.
 */
 void bloqr_validator_free(struct Validator *validator);

/**
 * Validates a local file (syntax + at-rest hash verification).
 *
 * On success or a validation failure, `*out_result_json` is set to an
 * owned, null-terminated JSON string describing the result (or the error)
 * which the caller must free with [`bloqr_validator_free_string`].
 *
 * # Safety
 *
 * `validator` must be a live handle from [`bloqr_validator_new`]. `path`
 * must point to a valid null-terminated UTF-8 C string. `out_result_json`
 * must point to valid, writable memory for a `*mut c_char`.
 */

FfiStatus bloqr_validator_validate_local_file(struct Validator *validator,
                                              const char *path,
                                              char **out_result_json);

/**
 * Validates a local file (syntax + at-rest hash verification) against a specific
 * [`ValidationEngine`], overriding whatever engine the validator was constructed with.
 *
 * `engine` must be `"dns"` or `"browser"` (case-insensitive); any other value (including
 * `NULL`) is treated as invalid UTF-8/an unrecognized engine and returns
 * [`FfiStatus::InvalidUtf8`]. This is the FFI-boundary counterpart of
 * [`Validator::validate_local_file_with_engine`] - see that function's docs, and
 * `docs/adr/0005-browser-syntax-validation-engine.md`, for what each engine accepts.
 *
 * On success or a validation failure, `*out_result_json` is set to an owned,
 * null-terminated JSON string describing the result (or the error) which the caller must
 * free with [`bloqr_validator_free_string`].
 *
 * # Safety
 *
 * `validator` must be a live handle from [`bloqr_validator_new`]. `path` and `engine` must
 * each point to a valid null-terminated UTF-8 C string. `out_result_json` must point to
 * valid, writable memory for a `*mut c_char`.
 */

FfiStatus bloqr_validator_validate_local_file_with_engine(struct Validator *validator,
                                                           const char *path,
                                                           const char *engine,
                                                           char **out_result_json);

/**
 * Validates a remote URL (security checks, HTTPS enforcement, optional
 * in-flight hash verification).
 *
 * `expected_hash` may be `NULL` to skip in-flight hash verification.
 *
 * On success or a validation failure, `*out_result_json` is set to an
 * owned, null-terminated JSON string describing the result (or the error)
 * which the caller must free with [`bloqr_validator_free_string`].
 *
 * # Safety
 *
 * `validator` must be a live handle from [`bloqr_validator_new`]. `url`
 * must point to a valid null-terminated UTF-8 C string; `expected_hash`
 * must be either `NULL` or a valid null-terminated UTF-8 C string.
 * `out_result_json` must point to valid, writable memory for a
 * `*mut c_char`.
 */

FfiStatus bloqr_validator_validate_remote_url(const struct Validator *validator,
                                              const char *url,
                                              const char *expected_hash,
                                              char **out_result_json);

/**
 * Returns the library version as an owned, null-terminated C string.
 *
 * The caller must free the returned string with
 * [`bloqr_validator_free_string`].
 */
 char *bloqr_validator_version(void);

/**
 * Frees a string previously returned by any `bloqr_validator_*` function
 * (via an `out_result_json` parameter, or [`bloqr_validator_version`]).
 *
 * # Safety
 *
 * `s` must be a pointer previously returned by one of this module's
 * functions and not already freed. Passing `NULL` is a no-op.
 */
 void bloqr_validator_free_string(char *s);

#endif  /* BLOQR_VALIDATOR_H */
