using System.Text;

namespace Bloqr.Dashboard.Core.Configuration;

/// <summary>
/// Emits a compiler config as a heavily-commented <c>.jsonc</c> document, for the wizard's (#268)
/// JSONC output option. Mirrors <see cref="JsoncWriter"/>'s hand-rolled, always-regenerate-in-full
/// approach: the wizard fully owns the shape of a config it just generated, so - unlike a
/// hand-authored file the wizard might later re-open - there's no third-party-authored content
/// whose comments must be preserved across a round trip.
/// </summary>
public static class CompilerConfigJsoncWriter
{
    /// <summary>
    /// Renders a <see cref="CompilerConfiguration"/> as a heavily-commented JSONC document.
    /// </summary>
    /// <param name="configuration">The configuration to render.</param>
    /// <returns>The JSONC document text.</returns>
    public static string Write(CompilerConfiguration configuration)
    {
        ArgumentNullException.ThrowIfNull(configuration);

        var sb = new StringBuilder();

        sb.AppendLine("// Bloqr rules-compiler configuration file.");
        sb.AppendLine("// Generated by the Bloqr Dashboard's compiler-config wizard.");
        sb.AppendLine("// Schema: https://github.com/BloqrAI/bloqr-core/schemas/compiler-config.schema.json");
        sb.AppendLine("{");

        AppendLine(sb, 1, "// Filter list name (required).");
        AppendLine(sb, 1, $"\"name\": {JsonString(configuration.Name)},");
        Blank(sb);

        if (!string.IsNullOrWhiteSpace(configuration.Description))
        {
            AppendLine(sb, 1, "// Filter list description.");
            AppendLine(sb, 1, $"\"description\": {JsonString(configuration.Description)},");
            Blank(sb);
        }

        if (!string.IsNullOrWhiteSpace(configuration.Homepage))
        {
            AppendLine(sb, 1, "// Homepage URL.");
            AppendLine(sb, 1, $"\"homepage\": {JsonString(configuration.Homepage)},");
            Blank(sb);
        }

        if (!string.IsNullOrWhiteSpace(configuration.License))
        {
            AppendLine(sb, 1, "// License identifier (e.g., MIT, Apache-2.0, ISC).");
            AppendLine(sb, 1, $"\"license\": {JsonString(configuration.License)},");
            Blank(sb);
        }

        if (!string.IsNullOrWhiteSpace(configuration.Version))
        {
            AppendLine(sb, 1, "// Version number (MAJOR.MINOR.PATCH).");
            AppendLine(sb, 1, $"\"version\": {JsonString(configuration.Version)},");
            Blank(sb);
        }

        if (configuration.Output is { } output)
        {
            AppendLine(sb, 1, "// Where the compiled output is published, and what happens when that file already exists:");
            AppendLine(sb, 1, "// \"rename\" (write alongside as name_1.txt, name_2.txt, ...), \"overwrite\" (replace it,");
            AppendLine(sb, 1, "// archiving the old file first if archiving is enabled below), or \"error\" (fail instead).");
            AppendLine(sb, 1, "\"output\": {");
            AppendLine(sb, 2, $"\"path\": {JsonString(output.Path)},");
            AppendLine(sb, 2, $"\"conflictStrategy\": {JsonString(output.ConflictStrategy)}");
            AppendLine(sb, 1, "},");
            Blank(sb);
        }

        if (configuration.HashVerification is { } hashVerification)
        {
            AppendLine(sb, 1, "// Hash-verification policy against the .hashes.json sidecar database. Mode is one of");
            AppendLine(sb, 1, "// \"strict\" (a mismatch always fails), \"warning\" (a mismatch is logged but compilation");
            AppendLine(sb, 1, "// continues), or \"disabled\" (no verification, though hashes are still computed).");
            AppendLine(sb, 1, "\"hashVerification\": {");
            AppendLine(sb, 2, $"\"mode\": {JsonString(hashVerification.Mode)},");
            AppendLine(sb, 2, $"\"requireHashesForRemote\": {JsonBool(hashVerification.RequireHashesForRemote)},");
            AppendLine(sb, 2, $"\"failOnMismatch\": {JsonBool(hashVerification.FailOnMismatch)},");
            AppendLine(sb, 2, $"\"hashDatabasePath\": {JsonString(hashVerification.HashDatabasePath)}");
            AppendLine(sb, 1, "},");
            Blank(sb);
        }

        if (configuration.Archiving is { } archiving)
        {
            AppendLine(sb, 1, "// Archiving policy applied when publishing overwrites an existing output file.");
            AppendLine(sb, 1, "\"archiving\": {");
            AppendLine(sb, 2, $"\"enabled\": {JsonBool(archiving.Enabled)},");
            AppendLine(sb, 2, $"\"mode\": {JsonString(archiving.Mode)},");
            AppendLine(sb, 2, $"\"retentionDays\": {JsonNumber(archiving.RetentionDays)}");
            AppendLine(sb, 1, "},");
            Blank(sb);
        }

        if (!string.IsNullOrWhiteSpace(configuration.DefaultEngine))
        {
            AppendLine(sb, 1, "// Fallback compilation engine/grammar for sources with no explicit \"engine\" of their");
            AppendLine(sb, 1, "// own and no strong content signal either way: \"dns\" (server-side/hosts-style rules) or");
            AppendLine(sb, 1, "// \"browser\" (client-side/cosmetic AdGuard syntax). Omit to fall back to \"dns\".");
            AppendLine(sb, 1, $"\"defaultEngine\": {JsonString(configuration.DefaultEngine)},");
            Blank(sb);
        }

        AppendLine(sb, 1, "// Filter sources to compile (required, at least one).");
        if (configuration.Sources.Count == 0)
        {
            AppendLine(sb, 1, "\"sources\": [],");
        }
        else
        {
            AppendLine(sb, 1, "\"sources\": [");
            AppendSources(sb, 2, configuration.Sources);
            AppendLine(sb, 1, "],");
        }
        Blank(sb);

        AppendLine(sb, 1, "// Global transformations applied to all sources' output.");
        AppendLine(sb, 1, $"\"transformations\": {JsonStringArray(configuration.Transformations)},");
        Blank(sb);

        AppendLine(sb, 1, "// Global inclusion patterns.");
        AppendLine(sb, 1, $"\"inclusions\": {JsonStringArray(configuration.Inclusions)},");
        Blank(sb);

        AppendLine(sb, 1, "// Local .txt files (in the Dashboard's dedicated pattern-files directory) containing");
        AppendLine(sb, 1, "// global inclusion patterns, one per line.");
        AppendLine(sb, 1, $"\"inclusions_sources\": {JsonStringArray(configuration.InclusionsSources)},");
        Blank(sb);

        AppendLine(sb, 1, "// Global exclusion patterns.");
        AppendLine(sb, 1, $"\"exclusions\": {JsonStringArray(configuration.Exclusions)},");
        Blank(sb);

        AppendLine(sb, 1, "// Local .txt files (in the Dashboard's dedicated pattern-files directory) containing");
        AppendLine(sb, 1, "// global exclusion patterns, one per line.");
        AppendLine(sb, 1, $"\"exclusions_sources\": {JsonStringArray(configuration.ExclusionsSources)}");

        sb.Append('}');
        sb.AppendLine();
        return sb.ToString();
    }

    private static void AppendSources(StringBuilder sb, int level, List<FilterSource> sources)
    {
        for (var i = 0; i < sources.Count; i++)
        {
            var source = sources[i];
            var isLast = i == sources.Count - 1;

            AppendLine(sb, level, "{");
            AppendLine(sb, level + 1, $"\"name\": {JsonString(source.Name)},");
            AppendLine(sb, level + 1, $"\"source\": {JsonString(source.Source)},");
            AppendLine(sb, level + 1, $"\"type\": {JsonString(source.Type)},");
            if (!string.IsNullOrWhiteSpace(source.Engine))
            {
                // Per-source engine override; unset means "auto-detect from content, falling back
                // to the config's defaultEngine, falling back to dns" (see FilterSource.Engine).
                AppendLine(sb, level + 1, $"\"engine\": {JsonString(source.Engine)},");
            }

            AppendLine(sb, level + 1, $"\"transformations\": {JsonStringArray(source.Transformations)},");
            AppendLine(sb, level + 1, $"\"inclusions\": {JsonStringArray(source.Inclusions)},");
            AppendLine(sb, level + 1, $"\"inclusions_sources\": {JsonStringArray(source.InclusionsSources)},");
            AppendLine(sb, level + 1, $"\"exclusions\": {JsonStringArray(source.Exclusions)},");
            AppendLine(sb, level + 1, $"\"exclusions_sources\": {JsonStringArray(source.ExclusionsSources)}");
            AppendLine(sb, level, isLast ? "}" : "},");
        }
    }

    private static void AppendLine(StringBuilder sb, int level, string text)
    {
        sb.Append(' ', level * 2);
        sb.AppendLine(text);
    }

    private static void Blank(StringBuilder sb) => sb.AppendLine();

    private static string JsonString(string? value) =>
        value is null ? "null" : JsonSerializer.Serialize(value);

    private static string JsonBool(bool value) => value ? "true" : "false";

    private static string JsonNumber(int value) => value.ToString(System.Globalization.CultureInfo.InvariantCulture);

    private static string JsonStringArray(List<string> values) =>
        values.Count == 0 ? "[]" : $"[{string.Join(", ", values.Select(JsonString))}]";
}
